spring.application.name=pesquisaeleitoral
ibge.api.base-url=https://servicodados.ibge.gov.br/api/v1/localidades
ibge.sidra.base-url=https://servicodados.ibge.gov.br/api/v3
ibge.sync.cron=0 0 3 1 * *
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*
